version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      FLASK_SECRET_KEY: "7a8c9b7d467e5b2f9f759ce502e5b6fa"
      DB_PATH: "/app/database/plates.db"
      RTSP_URL: "0"
    volumes:
      - ./models:/app/models
      - ./database:/app/database
      - ./logs:/app/logs
    restart: unless-stoppeds